Add missing include.
Fixes the following compilation errors with gcc 4.7 and later.

messageserver.cpp: In static member function 'static void MessageServer::hupSignalHandler(int)':
messageserver.cpp:501:5: error: '::write' has not been declared
messageserver.cpp: In member function 'void MessageServer::handleSigHup()':
messageserver.cpp:508:5: error: '::read' has not been declared

Change-Id: I6fbcf2cba884f5e285c0259e020c60f4a44173b4
Reviewed-by: Valerio Valerio <valerio.valerio@jollamobile.com>
Reviewed-by: Robin Burchell <robin+qt@viroteck.net>